name: skydata_studio
version: 0.1.0
config-version: 2

profile: skydata_studio

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: target
clean-targets: ["target", "dbt_packages"]

models:
  skydata_studio:
    staging:
      +materialized: view
      +schema: dbt_staging
      +tags: ["phase6", "dff", "staging"]
    intermediate:
      +materialized: view
      +schema: dbt_intermediate
      +tags: ["phase6", "dff", "intermediate"]
    marts:
      +materialized: table
      +schema: dbt_mart
      +tags: ["phase6", "dff", "mart"]
